version: '3.6'
services:

  hblink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hblink
    environment:
      - TZ=Europe/Paris
    ports:
      - 55550-55580:55550-55580/udp
    volumes:
      - ./hblink.cfg:/opt/hblink3/hblink.cfg:ro
      - ./HB_Bridge.cfg:/opt/hblink3/HB_Bridge.cfg:ro
      - ./rules.py:/opt/hblink3/rules.py
    networks:
      hblink:
        ipv4_address: 10.10.1.2
    restart: unless-stopped

  hbmonitor:
    build:
      context: .
      dockerfile: Dockerfile.hbmonitor
    container_name: hbmonitor
    depends_on:
      - hblink
    ports:
      - 8080:8080
      - 9000:9000
    volumes:
      - ./config.py:/opt/HBmonitor/config.py
    environment:
      - TZ=Europe/Paris      
    networks:
      hblink:
        ipv4_address: 10.10.1.3
    restart: unless-stopped

networks:
  hblink:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24        
        
